# Aplicacion
spring.application.name=alquilatusvehiculos

# H2 - Base de datos
spring.datasource.url=jdbc:h2:mem:alquiladb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 - Consola web http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Thymeleaf
spring.thymeleaf.cache=false

#fakeDataSQL
spring.sql.init.mode=always



